version: '3.4'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"

  mongodb:
    image: mongo:4
    restart: always
    volumes:
      - ./.data/db:/data/db
    ports:
      - "27018:27017"

  backend:
    container_name: backend
    build: .
    env_file:
      - .env.docker
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    depends_on:
      - mongodb
      - redis
    entrypoint: "./docker-entrypoint.sh"

  sidekiq:
    links:
      - redis
    build: .
    env_file:
      - .env.docker
    command: bundle exec sidekiq
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app

  ws:
    image: anycable/anycable-go:1.2
    ports:
      - '9293:8080'
    env_file:
      - .env.docker

  anycable:
    build: .
    command: bundle exec anycable
    env_file:
      - .env.docker
    ports:
      - '50051'
    volumes:
      - .:/app
    depends_on:
      - backend