version: '3.4'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./.data/db:/data/db
    ports:
      - "27018:27017"

  backend:
    container_name: backend
    build: .
    env_file:
      - .docker_env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - mongodb
      - redis

  sidekiq:
    links:
      - mongodb
      - redis
    build: .
    env_file:
      - .docker_env
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - .:/app/tmp

  ws:
    image: anycable/anycable-go:1.2
    ports:
      - '8080:8080'
    env_file:
      - .docker_env

  anycable:
    build: .
    command: bundle exec anycable
    env_file:
      - .docker_env
    environment:
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
    ports:
      - '50051'
