default: &default
  access_logs_disabled: false
  rpc_host: "127.0.0.1:50051"
  log_grpc: false
  broadcast_adapter: redis
  redis_channel: "__anycable__"
  redis_url: <%= ENV['REDIS_URL'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
