development:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>

test:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>
