development:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>

test:
  clients:
    default:
      database: retrosprint_test
      hosts:
        - <%= ENV['MONGO_ADDR'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>
