development:
  clients:
    default:
      database: retrosprint_development
      hosts:
        - <%= ENV['MONGO_ADDR'] %>
      options:
        user: root
        password: qwerty
        auth_source: admin
test:
  clients:
    default:
      database: retrosprint_test
      hosts:
        - <%= ENV['MONGO_ADDR'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
